name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
    
      - name: Installing Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
        
      - name: Set github secrets
        run: git config --global url."https://${{ secrets.PAT }}@github.com/".insteadOf ssh://git@github.com/
          
      - name: Install Dependencies
        run: npm install
        
      - name: Building APP
        run: npm run build
        
      - name: Running Jest Coverage
        run: npm run test:cov
