name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Installing Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Building APP
        run: npm run build
        
      - name: Running Jest Coverage
        run: npm run test:cov
